# Generated by Django 4.2.16 on 2024-12-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('L', 'Низкий'), ('M', 'Средний'), ('H', 'Высокий')], max_length=100),
        ),
    ]
